# Generated by Django 5.0.3 on 2024-03-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsheetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsheet',
            name='description',
            field=models.TextField(default='Default description', max_length=2000),
        ),
    ]
